### ISSUE TITLE
If you connect a Gamepad after the game already started it breaks input.

### ISSUE THREAD

**Issue by michaelsakharov** [BxB-Studio/Inputs-Manager#1]
As the title says if your ingame in the editor (Havent tested a build) and connect a Gamepad, it breaks input.

**Comment by yboumaiza** [comment]
Do you mean the Unity Editor crashes? Or it just outputs an error?

**Comment by yboumaiza** [comment]
Bug fixed on `1.0.1`

Please confirm once you update the Inputs Manager, so we can close this issue.

Edit: Using a PS3 Driver Emulator on PCs might be the issue; You may have to plug & unplug the PS3 Controller multiple times while in Play Mode for it to be detected.

**Comment by michaelsakharov** [comment]
Seems fixed!
