### ISSUE TITLE
Rebinding Inputs in Runtime

### ISSUE THREAD

**Issue by michaelsakharov** [BxB-Studio/Inputs-Manager#2]
Was looking around trying to find any way to change (And save/load) rebinds during runtime, doesn't seem like there is any? Would be nice to be able to have Ingame Rebind settings and to save said settings in PlayerPrefs. The Github Description does say "Edit in Runtime" So I might just be Blind and cant find anything.

**Comment by yboumaiza** [comment]
Editing Inputs at Runtime is ONLY available through scripting _(That might need to be clearer in `README.md` though)_.
The API documentation is still not available for the moment, which might be the greater issue here,
but I've tried taking into consideration nearly every case related to what's mentioned in the `README.md` file.
Although, the API needs some workaround to enhance accessing & editing keys...

To edit an Input use the following code:
```
// Retreive an input named "Vertical"
Input input = InputsManager.GetInput("Vertical");
// Retreive an input with index 0; Using names might be better as inputs can be sorted within the InputsManager editor
Input input = InputsManager.GetInput(0);

// Edit the positive key of the main axis of the input
input.Main.Positive = Key.A;

// Editing the axis strongest side is not possible at Runtime
input.Main.StrongSide = Side.Negative;

// Assigning an axis to the input directly is not possible at Runtime
input.Main = new Axis();
```

Saving the `InputsManager` data at Runtime would override the Game's original data which is not practical.
To save/load/delete Runtime edits use the following code:
```
// The `DataSheet` object contains the current `InputsManager` settings per default
DataSheet saveData = new DataSheet();

// Using DataSerializationUtility
using Utilities; // Required namespace

string fullPath = "your/save/path/and/filename";

DataSerializationUtility<DataSheet> serializer = new DataSerializationUtility<DataSheet>(fullPath, false);

serializer.SaveOrCreate(saveData); // To save
serializer.Delete(); // To delete

DataSheet loadedData = serializer.Load(); // To load

// Using Json & PlayerPrefs
using UnityEngine; // Required namespace

// Save
string saveJson = JsonUtility.ToJson(saveData);
string prefKey = "PREF_KEY";

PlayerPrefs.SetString(prefKey, json);

//Delete
PlayerPrefs.DeleteKey(prefKey);

// Load
string loadJson = PlayerPrefs.GetString(prefKey);

DataSheet loadedData = JsonUtility.FromJson<DataSheet>(loadJson);

// Assign loaded inputs to the InputsManager
foreach (Input inputData in loadedData.Inputs)
{
	Input input = InputsManager.GetInput(inputData.Name);

	input.Main.Positive = inputData.Main.Positive;
	input.Main.Negative = inputData.Main.Negative;
	input.Alt.Positive = inputData.Alt.Positive;
	input.Alt.Negative = inputData.Alt.Negative;
	input.Main.GamepadPositive = inputData.Main.GamepadPositive;
	input.Main.GamepadNegative = inputData.Main.GamepadNegative;
	input.Alt.GamepadPositive = inputData.Alt.GamepadPositive;
	input.Alt.GamepadNegative = inputData.Alt.GamepadNegative;
}
```

P.S: a method to apply a `DataSheet` object to the `InputsManager` directly seems to be a necessity; I'll add it in a future release :)

**Comment by michaelsakharov** [comment]
Awesome! Thanks.

**Comment by yboumaiza** [comment]
You're welcome :D

**Comment by yboumaiza** [comment]
I've updated the InputsManager to meet the newest requirements.
Check out the change log for the new version to find out what's new :D
